const FoodData = [
    {
        id: 1,
        img:"https://b.zmtcdn.com/data/dish_photos/06d/a1a769185079a88521f719d4f136506d.jpg",
        name: "Bhaiya Ji's Biryani c" ,
        price: 150 ,
        desc:  "Serves 1 | A combination of juicy Sweet Corn & 100% mozzarella cheese with flavourful signature pan sauce. (PAN Per-320Kcal/100g)" ,
        category: "Chicken",
        rating: 4.5 ,
    },
    {
        id: 2,
        img: "https://b.zmtcdn.com/data/dish_photos/dcf/6e18264f5d9e32f0c6acc4646fbbcdcf.jpg",
        name: "Aman Dhaba c" ,
        price: 250 ,
        desc:  "Cheese Dip, Jalapeno Dip, Capsicum, Paneer, Onion, Sweet Corn, Mushroom [Fat-11.3 per 100 g, Protein-8.7 per 100 g, Carbohydrate-33.4 per 100 g, Sugar-2 per 100 g, Calories-270 k.cal]Nutritional information per 100g" ,
        category: "Chicken",
        rating: 4.5 ,
    },
    {
        id: 3,
        img:"https://b.zmtcdn.com/data/dish_photos/aa9/fe8319bd588cecafb53fd1bc41faeaa9.jpg",
        name: "Al Lazeez Biryani c" ,
        price: 180 ,
        desc:  "Hot passion on a Pizza. Jalapenos, Mushrooms, Red Paprika, Fresh Tomato With Jalapeno Dip. [Fat-6.5 per 100 g, Protein-6.1 per 100 g, Carbohydrate-45 per 100 g, Sugar-0 per 100 g, Calories-263.2 k.cal]Nutritional information per 100g" ,
        category: "Chicken",
        rating: 5.5 ,
    },
    {
        id: 4,
        img:"https://b.zmtcdn.com/data/dish_photos/bb1/a3f79488ae42b312103dd3f87c93abb1.jpg",
        name: "Dhillon Chicken c" ,
        price: 190 ,
        desc:  "Capsicum, Sweet Corn, Red Paprika, Double Paneer With Korma Dip" ,
        category: "Chicken",
        rating: 4.1 ,
    },
    {
        id: 5,
        img:"https://b.zmtcdn.com/data/dish_photos/292/5340590e1c38254c988fd85a25019292.jpg",
        name: "Madhurisha Family Restaurant c" ,
        price: 110 ,
        desc:  "Onion ,Capsicum, Mushroom, Sweet Corn, Jalapenos In Pesto & Basil Sauce" ,
        category: "Chicken",
        rating: 3.1 ,
    },
    {
        id: 6,
        img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/tyddr0w43n0zytfyjhty",
        name: "Corn pizza",
        price: 190 ,
        desc:  "Delicious and flavorful noodles with a delightful twist, perfect for veggie lovers." ,
        category: "Pizza",
        rating: 4.0 ,
    },
    {
        id: 7,
        img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/07791f77b2c9961076239bf00f52d0f3",
        name: "Cad M Cad B p" ,
        price: 150 ,
        desc:  "Serves 1 | A combination of juicy Sweet Corn & 100% mozzarella cheese with flavourful signature pan sauce. (PAN Per-320Kcal/100g)" ,
        category: "Pizza",
        rating: 4.5 ,
    },
    {
        id: 8,
        img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/3/22/8e746808-db3f-4596-a910-337367ef3be4_d53fc1bb-bce2-421b-ad84-3bf18e4a00b2.jpg",
        name: "Cheese Lovers Pizza Regular " ,
        price: 250 ,
        desc:  "Cheese Dip, Jalapeno Dip, Capsicum, Paneer, Onion, Sweet Corn, Mushroom [Fat-11.3 per 100 g, Protein-8.7 per 100 g, Carbohydrate-33.4 per 100 g, Sugar-2 per 100 g, Calories-270 k.cal]Nutritional information per 100g" ,
        category: "Pizza",
        rating: 4.5 ,
    },
    {
        id: 9,
        img:"https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/mgouviv7vexhodvqqozt",
        name: "Hot Passion Pizza Regular" ,
        price: 180 ,
        desc:  "Hot passion on a Pizza. Jalapenos, Mushrooms, Red Paprika, Fresh Tomato With Jalapeno Dip. [Fat-6.5 per 100 g, Protein-6.1 per 100 g, Carbohydrate-45 per 100 g, Sugar-0 per 100 g, Calories-263.2 k.cal]Nutritional information per 100g" ,
        category: "Pizza",
        rating: 5.5 ,
    },
    {
        id: 10,
        img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/5bee918fe4bb11fca0ef97f15a2612af",
        name: "Tandoori Special Pizza Regular" ,
        price: 190 ,
        desc:  "Capsicum, Sweet Corn, Red Paprika, Double Paneer With Korma Dip" ,
        category: "Pizza",
        rating: 4.1 ,
    },
    {
        id: 11,
        img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/e0ed25c02f8882bc8e80edb950cf31ab",
        name: "Pesto & Basil Special Pizza Regular" ,
        price: 110 ,
        desc:  "Onion ,Capsicum, Mushroom, Sweet Corn, Jalapenos In Pesto & Basil Sauce" ,
        category: "Pizza",
        rating: 3.1 ,
    },
    {
        id: 12,
        img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/tyddr0w43n0zytfyjhty",
        name: "Cake pizza" ,
        price: 190 ,
        desc:  "Delicious and flavorful noodles with a delightful twist, perfect for veggie lovers." ,
        category: "Pizza",
        rating: 4.0 ,
    },
    {
        id: 13,
        img:"https://b.zmtcdn.com/data/dish_photos/ae1/b98158b266886a98c4193a3a89fabae1.jpg",
        name: "The 90s burger" ,
        price: 150 ,
        desc:  "Serves 1 | A combination of juicy Sweet Corn & 100% mozzarella cheese with flavourful signature pan sauce. (PAN Per-320Kcal/100g)" ,
        category: "Burger",
        rating: 4.5 ,
    },
    {
        id: 14,
        img:"https://b.zmtcdn.com/data/pictures/6/21000276/726cce270d41b2988f1944299e30ed0d_o2_featured_v2.jpg",
        name: "Eat & Bite burger" ,
        price: 250 ,
        desc:  "Cheese Dip, Jalapeno Dip, Capsicum, Paneer, Onion, Sweet Corn, Mushroom [Fat-11.3 per 100 g, Protein-8.7 per 100 g, Carbohydrate-33.4 per 100 g, Sugar-2 per 100 g, Calories-270 k.cal]Nutritional information per 100g" ,
        category: "Burger",
        rating: 4.5 ,
    },
    {
        id: 15,
        img:"https://b.zmtcdn.com/data/dish_photos/017/8824610521847d3cdaba501f1b567017.jpeg",
        name: "Chizze Burger" ,
        price: 180 ,
        desc:  "Hot passion on a Pizza. Jalapenos, Mushrooms, Red Paprika, Fresh Tomato With Jalapeno Dip. [Fat-6.5 per 100 g, Protein-6.1 per 100 g, Carbohydrate-45 per 100 g, Sugar-0 per 100 g, Calories-263.2 k.cal]Nutritional information per 100g" ,
        category: "Burger",
        rating: 5.5 ,
    },
    {
        id: 16,
        img:"https://b.zmtcdn.com/data/pictures/0/20997360/49d84aa892af41ad9981b2dd135922b2_o2_featured_v2.jpg",
        name: "Burger Singh - Big Punjabi Burger" ,
        price: 190 ,
        desc:  "Capsicum, Sweet Corn, Red Paprika, Double Paneer With Korma Dip" ,
        category: "Burger",
        rating: 4.1 ,
    },
    {
        id: 17,
        img:"https://b.zmtcdn.com/data/dish_photos/7ac/7c792200b6d15618fb3d370e561557ac.jpg",
        name: "Grill Inn Burger" ,
        price: 110 ,
        desc:  "Onion ,Capsicum, Mushroom, Sweet Corn, Jalapenos In Pesto & Basil Sauce" ,
        category: "Burger",
        rating: 3.1 ,
    },
    {
        id: 18,
        img:"https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/ongqbindk1f7jvfu6e02",
        name: "Young Tarang dosa" ,
        price: 150 ,
        desc:  "Serves 1 | A combination of juicy Sweet Corn & 100% mozzarella cheese with flavourful signature pan sauce. (PAN Per-320Kcal/100g)" ,
        category: "Dosa",
        rating: 4.5 ,
    },
    {
        id: 19,
        img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/76726bf93b698924f2a7ea995f1f342b",
        name: "Mr Anna by Maa ki Rasoi dosa" ,
        price: 250 ,
        desc:  "Cheese Dip, Jalapeno Dip, Capsicum, Paneer, Onion, Sweet Corn, Mushroom [Fat-11.3 per 100 g, Protein-8.7 per 100 g, Carbohydrate-33.4 per 100 g, Sugar-2 per 100 g, Calories-270 k.cal]Nutritional information per 100g" ,
        category: "Dosa",
        rating: 4.5 ,
    },
    {
        id: 20,
        img:"https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/ffb11c5e470017952bf4ab27a98d6272",
        name: "Al Dosa magic" ,
        price: 180 ,
        desc:  "Hot passion on a Pizza. Jalapenos, Mushrooms, Red Paprika, Fresh Tomato With Jalapeno Dip. [Fat-6.5 per 100 g, Protein-6.1 per 100 g, Carbohydrate-45 per 100 g, Sugar-0 per 100 g, Calories-263.2 k.cal]Nutritional information per 100g" ,
        category: "Dosa",
        rating: 5.5 ,
    },
    {
        id: 21,
        img:"https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/743fc93284806c87a23f2e85326a2f55",
        name: "Indian dosa" ,
        price: 190 ,
        desc:  "Capsicum, Sweet Corn, Red Paprika, Double Paneer With Korma Dip" ,
        category: "Dosa",
        rating: 4.1 ,
    },
    {
        id: 22,
        img:"https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/9e58e6eee8806a706dde5dd1f1d17ac6",
        name: "Dosa with chatni" ,
        price: 110 ,
        desc:  "Onion ,Capsicum, Mushroom, Sweet Corn, Jalapenos In Pesto & Basil Sauce" ,
        category: "Dosa",
        rating: 3.1 ,
    },
    
]   
export default FoodData